### ISSUE TITLE
Option -pt lasso causing failure

### ISSUE THREAD

**Issue by Strep** [thedamlab/rodeo2#1]
`python rodeo_main.py -out no_pt_out BAL72546`
works fine and produces the output included as no_pt.html in the attached rodeo2err.zip But

`python rodeo_main.py -out lasso_out -pt lasso BAL72546`
fails. rodeo_main.err, rodeo_main.out and lasso_pt.html  are also included in rodeo2err.zip
[rodeo2err.zip](https://github.com/thedamlab/rodeo2/files/1522474/rodeo2err.zip)

Use of the `-pt lanthi` also gives similar error even when `-hmm <path_to_TIGRFAM.hmm>` is used.

Python version is 2.7.5.

**Comment by bkille** [comment]
Strep,

Sorry for the late response. I am new to managing github repos. I believe that error should be fixed at this point. Are you still having this issue?
